name: portfolio

services:
  postgres:
    image: docker.io/library/postgres
    container_name: portfolio-db
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-api
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://portfolio_user:${POSTGRES_PASSWORD}@postgres:5432/portfolio
    expose:
      - "8000"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - frankslab-uk
      - internal
    deploy:
      resources:
        limits:
          memory: 1gib

volumes:
  postgres_data:

networks:
  frankslab-uk:
    external: true
  internal:

