[project]
name = "portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michael Franks", email = "mffranks@pm.me" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "asyncmy>=0.2.14",
    "asyncpg>=0.31.0",
    "bleach>=6.4.0",
    "fastapi>=0.141.1",
    "markdown>=3.10.3",
    "passlib>=1.7.4",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "slowapi>=0.1.10",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
portfolio = "portfolio:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
